<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DotCelery.Backend.SqlServer</RootNamespace>
    <Description>SQL Server result backend and stores for DotCelery</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotCelery.Core\DotCelery.Core.csproj" />
    <ProjectReference Include="..\DotCelery.Storage.Sql\DotCelery.Storage.Sql.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.12" />
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.401" />
  </ItemGroup>
</Project>
